// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBIAGFDp7bLO2y6YBIg7PiiETJwYx341U',
    appId: '1:438353375032:web:f2c4c03ca10b97baca5bcd',
    messagingSenderId: '438353375032',
    projectId: 'eyego-task',
    authDomain: 'eyego-task.firebaseapp.com',
    storageBucket: 'eyego-task.firebasestorage.app',
    measurementId: 'G-Y5PJLMLKTN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV14g30-xwq3USbyyBVem4F6lh92qQn_8',
    appId: '1:438353375032:android:ca18aeb7612c07a5ca5bcd',
    messagingSenderId: '438353375032',
    projectId: 'eyego-task',
    storageBucket: 'eyego-task.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnW0HAZELPgWQL9OuGL2z5U4PF_bQb2l0',
    appId: '1:438353375032:ios:09880d23bfb8f3cfca5bcd',
    messagingSenderId: '438353375032',
    projectId: 'eyego-task',
    storageBucket: 'eyego-task.firebasestorage.app',
    iosBundleId: 'com.example.eyegoTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnW0HAZELPgWQL9OuGL2z5U4PF_bQb2l0',
    appId: '1:438353375032:ios:09880d23bfb8f3cfca5bcd',
    messagingSenderId: '438353375032',
    projectId: 'eyego-task',
    storageBucket: 'eyego-task.firebasestorage.app',
    iosBundleId: 'com.example.eyegoTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBIAGFDp7bLO2y6YBIg7PiiETJwYx341U',
    appId: '1:438353375032:web:1fd3de4540475650ca5bcd',
    messagingSenderId: '438353375032',
    projectId: 'eyego-task',
    authDomain: 'eyego-task.firebaseapp.com',
    storageBucket: 'eyego-task.firebasestorage.app',
    measurementId: 'G-X53PJFYBMC',
  );
}
